 export const LOGIN_USER = "LOGIN_USER",
              LOGOUT_USER = "LOGOUT_USER",


              GET_PEDIDOS = "GET_PEDIDOS",
              CANCELAR_PEDIDO = "CANCELAR_PEDIDO",
              LIMPAR_PEDIDO = "LIMPAR_PEDIDO",
              GET_PEDIDO= "GET_PEDIDO",

              GET_CLIENTES = "GET_CLIENTES",
              GET_CLIENTE = "GET_CLIENTE",
              LIMPAR_CLIENTE ="LIMPAR_CLIENTE",
              GET_CLIENTE_PEDIDOS = "GET_CLIENTE_PEDIDOS",
              REMOVE_CLIENTE="REMOVE_CLIENTE",


              GET_CATEGORIAS = " GET_CATEGORIAS",
              GET_CATEGORIA = "GET_CATEGORIA",

              LIMPAR_CATEGORIA = "LIMPAR_CATEGORIA",
              GET_CATEGORIA_PRODUTOS = "GET_CATEGORIA_PRODUTOS",
              REMOVE_CATEGORIA = "REMOVE_CATEGORIA",

              GET_PRODUTOS = "GET_PRODUTOS",
              GET_PRODUTO = "GET_PRODUTO",
              LIMPAR_PRODUTO = "LIMPAR_PRODUTO"